### PR TITLE
Updated scripts to work with the services (IndexWorker, AutomationEngine, ProcessingEngine)

### PR DESCRIPTION
**Pull request by mwillebrands**
Hi,

The current sync scripts will not work with the services like IndexWorker, AutomationEngine and ProcessingEngine, as these services place a lock on the DLL files, and these services will not automatically restart when a config has changed.

This change changes the Watch-Directory script as follows:
- The script now starts the executable if it is passed
- When a file change is detected and we are running as service (based on the Executable parameter), the service is stopped
- The file changes are then synced
- The service is started

This change changes the Development.ps1 entrypoint script  for the worker as follows
- The entry point no longer starts the service itself
- The entry point passes the path to the executable to the Watch-Directory script

The changes make it possible to do continous development on the services instead of having to recreate the image all the time. The following entry point can now be passed from the docker-compose file:
```
  xdbautomationworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-xdbautomationworker:${VERSION:-latest}
    entrypoint: powershell -Command "& C:\tools\entrypoints\worker\Development.ps1 -WatchDirectoryParameters @{Path = 'c:\deploy\App_Data\jobs\continuous\AutomationEngine';Destination = 'c:\service'}"
```
The _c:\deploy\App_Data\jobs\continuous\AutomationEngine_ path in the above snippet is the path within the container to which my AutomationEngine files are deployed, and could of course be changed to something else or an environment variable.

### CODE REVIEW

**Comment by sc-olenanosenko** [comment]
Hi @mwillebrands !
Please, merge all updates from the 'main' branch to the 'mwillebrands:feature/ImprovedWorkerEntrypoint' to make sure that all checks passed.

**Comment by mwillebrands** [comment]
> Hi @mwillebrands ! Please, merge all updates from the 'main' branch to the 'mwillebrands:feature/ImprovedWorkerEntrypoint' to make sure that all checks passed.

Done, but it doesn't seem to work.

**Comment by sc-olenanosenko** [comment]
I see that all changes applied to your branch but have an issue in PowerShell tests.
Link to the file with an issue: https://github.com/Sitecore/docker-tools/blob/main/image/test/scripts/Watch-Directory.Tests.ps1 
Test "copies new files" doesn't work correctly. Should fix it.

**Comment by sc-olenanosenko** [comment]
@mwillebrands Thanks for the update, I will look at it.

**Pull request merged**
